import type { PostCardData } from "@/components/shared/PostCard";

const POST_TEXT =
  "Land prices in East Legon Hills are up nearly 12% this quarter. If you're thinking of buying in the next 6 months, now's worth a serious look.";

const CONSULT_TEXT =
  "New build wrapped this week — a 3-unit courtyard house in Trasacco. Full portfolio on my profile.";

// Shared across the full "/feed" post stream and the "/home" dashboard's
// condensed preview, so both surfaces stay backed by one source of dummy
// content (there's no real feed backend yet).
export const FEED_POSTS: PostCardData[] = [
  {
    id: "1",
    variant: "text",
    authorName: "Andy Ansong",
    roleLine: "Real Estate Consultant |",
    postedAt: "27m ago",
    avatar: "/icons/avatar-andy.png",
    verified: "individual",
    text: POST_TEXT,
    image: "/images/post-building-01.jpg",
    likes: 42,
    comments: 42,
    showComposer: true,
  },
  {
    id: "2",
    variant: "poll",
    authorName: "Edwin adu Boateng",
    roleLine: "Sales Agent |",
    postedAt: "2hrs ago",
    avatar: "",
    avatarPlaceholder: true,
    participantAvatars: ["/images/poll-avatar-1.png", "/images/poll-avatar-2.png", "/images/poll-avatar-3.png"],
    question: "What matters most when choosing a stay?",
    hashtags: "#quickquestion #plsanswer",
    pollOptions: [
      { label: "Amenities", percent: 55, votes: "1,418", leading: true },
      { label: "Price", percent: 25, votes: "4,587" },
      { label: "Location", percent: 12, votes: "1,418" },
      { label: "Reviews", percent: 8, votes: "487" },
    ],
    pollFooter: "Jun 25, 2026 — 12,157 votes total",
    likes: 12,
    comments: 25,
    shareLabel: "187 Share",
    showComposer: true,
  },
  {
    id: "3",
    variant: "property",
    authorName: "Kasapa Properties Ltd",
    roleLine: "Sponsored by agent |",
    postedAt: "40m ago",
    avatar: "/images/avatar-kasapa.png",
    verified: "organization",
    text: POST_TEXT,
    images: [
      "/images/post-building-01.jpg",
      "/images/post-property-exterior.jpg",
      "/images/post-property-living-room.jpg",
      "/images/post-property-kitchen.jpg",
      "/images/post-property-bedroom.jpg",
    ],
    priceLine: "GHS 1,850.00",
    priceSuffix: "/plot",
    subLine: "4 bedroom Detached House",
    beds: 4,
    baths: 2,
    actions: [
      { label: "Request viewing", variant: "primary" },
      { label: "View Property", variant: "outline" },
    ],
    messageHostLabel: "Message Host",
    likes: 42,
    comments: 42,
  },
  {
    id: "4",
    variant: "stay",
    authorName: "Golden Palm Hotel",
    roleLine: "Labadi |",
    postedAt: "1d",
    avatar: "/images/avatar-golden-palm.png",
    verified: "organization",
    image: "/images/post-hotel-pool.jpg",
    priceLine: "GHS 550.00",
    priceSuffix: "/night",
    subLine: "Deluxe room",
    rating: "4.7 ratings (312)",
    actions: [
      { label: "Book Now", variant: "primary" },
      { label: "Check Availability", variant: "outline" },
    ],
    likes: 42,
    comments: 42,
    showComposer: true,
  },
  {
    id: "5",
    variant: "professional",
    authorName: "Ama Boatengmaa",
    roleLine: "Architect - Studio Meridian |",
    postedAt: "27m ago",
    avatar: "/images/avatar-generic.png",
    verified: "individual",
    text: CONSULT_TEXT,
    image: "/images/post-building-01.jpg",
    actions: [
      { label: "Request Consultation", variant: "primary" },
      { label: "Message", variant: "outline" },
    ],
    messageHostLabel: "Message Host",
    likes: 42,
    comments: 42,
    showComposer: true,
  },
  {
    id: "6",
    variant: "artisan",
    authorName: "Yaw Osei",
    roleLine: "Electrician - Serves Accra |",
    postedAt: "27m ago",
    avatar: "/images/avatar-generic.png",
    verified: "individual",
    text: CONSULT_TEXT,
    image: "/images/post-building-01.jpg",
    actions: [
      { label: "Book Artisan", variant: "primary" },
      { label: "Bookmark Artisan", variant: "outline" },
    ],
    messageHostLabel: "Message Host",
    likes: 42,
    comments: 42,
    showComposer: true,
  },
  {
    id: "7",
    variant: "project",
    authorName: "Golden Ridge Developers",
    roleLine: "New Development |",
    postedAt: "3hrs ago",
    avatar: "/images/avatar-kasapa.png",
    verified: "organization",
    text: "Breaking ground on Golden Ridge Estates — 40 serviced plots with road network and utilities already in. Reserve a plot before the next price review.",
    image: "/images/post-building-01.jpg",
    actions: [
      { label: "Make Enquiry", variant: "primary" },
      { label: "View Project", variant: "outline" },
    ],
    messageHostLabel: "Message Host",
    likes: 42,
    comments: 42,
    showComposer: true,
  },
];
