# Generated by Django 6.0.1 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="media_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
