# Generated by Django 6.0.1 on 2026-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
