# Generated by Django 6.0.1 on 2026-03-23 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('property_purchase', 'Property Purchase'), ('hotel_booking', 'Hotel Booking'), ('artisan_payment', 'Artisan Payment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(default='paystack', max_length=32)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
