# Generated by Django 6.0.1 on 2026-04-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_paystack_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_hotel_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_hotels',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
