# Generated by Django 6.0.1 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="interval",
            field=models.CharField(default="monthly", max_length=20),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_artisan_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_image_size_mb",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_images",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_video_size_mb",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_videos",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="paystack_plan_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]