# Generated by Django 6.0.1 on 2026-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bathrooms', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.CharField(blank=True, help_text='Example: King Size Bed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.CharField(blank=True, help_text='Example: 1-2 Persons', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], help_text='Only required if the property is for rent', max_length=10, null=True),
        ),
    ]
